FROM node:16.19.0-buster-slim
RUN apt-get update && apt-get install -y \
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY ./twittr ./twittr

#build
#copy build files



#build step
FROM library/python:3.8-slim-buster

RUN apt-get update \
    # dependencies for building Python packages
    && apt-get install -y build-essential \
    # psycopg2 dependencies
    && apt-get install -y libpq-dev \
    # Translations dependencies
    && apt-get install -y gettext \
    && apt-get install -y libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info \
    # cleaning up unused files
    && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app/backend

COPY ./requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt \
    && rm -rf /requirements.txt

COPY . /usr/src/app/backend

EXPOSE 80
ARG SECRET_KEY
ARG CAPROVER_GIT_COMMIT_SHA
ENV SECRET_KEY=$SECRET_KEY
ENV CAPROVER_GIT_COMMIT_SHA=$CAPROVER_GIT_COMMIT_SHA

CMD ["sh", "./backend/runs.sh"]