name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
    - name: install Dependencies
      run: |
        cd /var/www/jobtweets.xyz/twittr
        pwd
        ls -a
        npm install
        npm run build
        cd ../backend
      with:
        source: "."
        target: "/var/www/jobtweets.xyz"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          pwd
          cd /var/www/jobtweets.xyz/twittr
          pwd
          ls -a

          



