name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        
      with:
        source: "."
        target: "/var/www/jobtweets.xyz"

    - name: Load private SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSHKEY }}

    - name: Atomic Deploy
      run: |
        ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} << EOF
          ls
        EOF